; PlatformIO project configuration
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv]
platform = espressif8266
board = nodemcu           ; swap for "nodemcuv2" or "esp12e" if using a different ESP8266 board
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit BusIO @ ^1.14.1
